Add an option to disable using LZO index files when computing splits
twitter/elephant-bird pull request #483
Opened 2017-06-19 14:24 UTC by steveniemitz

We have many jobs that read large (>10,000) numbers of LZO input files.  Because of the linear relationship of split calculation time to the number of inputs, some of these jobs can actually take longer to calculate the splits than for the mappers to actually run.

Results from an trivial test job show a massive speedup when disabling using indexes when calculating splits, with no change in the number of splits actually created.

With index files enabled:
``` 
 * RESULTS:          1
 *   input paths:  9708
 *   total splits: 4854
 *   time [s]:      165
```
and disabled:
```
 *  RESULTS:          1
 *   total paths:  9708
 *   total splits: 4854
 *   time [s]:        2
```

Internally we've been using hacky similar solution which involved overriding `getSplits()` from `MultiInputFormat` in a subclass.  While hacky, it has enabled a very significant speed up in many of our jobs.

As a follow up enhancement, we could automatically skip split calculation using LZO indexes if the number of input files is greater than some number N (which could be chosen via sampling many existing jobs).

Finally, another reason one would want to enable this feature is in cloud environments.  Typically cloud blob stores (S3, GCS) have a significantly higher time-to-first-byte than say, locally hosted HDFS.  Because of this, doing many small (LZO index files are typically only a few MB) sequential reads can be very slow.  I specifically ran into this running a job in Google Dataproc processing ~10,000 files, the time to calculate splits for the job took over 40 minutes!  Disabling splitting dropped the time to ~1 second.

2017-06-20 22:27 UTC, gerashegalov requested changes

2017-06-20 22:27 UTC, gerashegalov commented on core/src/main/java/com/twitter/elephantbird/mapreduce/input/LzoInputFormat.java
> +  private static final String USE_LZO_INDEX_FILES_KEY = "elephantbird.use.lzo.index.files";
I think what you want is to skip reading the index file if the split is an entire file or close to that instead of a binary switch that would behave poorly in one situation or the other.

2017-06-20 22:27 UTC, gerashegalov commented on core/src/main/java/com/twitter/elephantbird/mapreduce/input/LzoInputFormat.java
> +  private static final String USE_LZO_INDEX_FILES_KEY = "elephantbird.use.lzo.index.files";
we can compare file length to https://github.com/apache/hadoop/blob/trunk/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapreduce/lib/input/FileInputFormat.java#L388

2017-06-20 22:35 UTC, steveniemitz commented on core/src/main/java/com/twitter/elephantbird/mapreduce/input/LzoInputFormat.java
> +  private static final String USE_LZO_INDEX_FILES_KEY = "elephantbird.use.lzo.index.files";
Cool, that makes sense, then users can just crank up the min split size to get the same speedup.

2017-08-30 21:26 UTC, gerashegalov commented on core/src/main/java/com/twitter/elephantbird/mapreduce/input/LzoInputFormat.java
> +  private static final String USE_LZO_INDEX_FILES_KEY = "elephantbird.use.lzo.index.files";
@steveniemitz I feel your pain on my team as well. Are you going to work on this soon? We could use the same parameter as for the read path: https://github.com/twitter/elephant-bird/blob/fb2fa515e3f91e1dceab47eb05fe5eecd75bacd9/core/src/main/java/com/twitter/elephantbird/util/LzoUtils.java#L77

2017-08-31 14:35 UTC, steveniemitz commented on core/src/main/java/com/twitter/elephantbird/mapreduce/input/LzoInputFormat.java
> +  private static final String USE_LZO_INDEX_FILES_KEY = "elephantbird.use.lzo.index.files";
Yeah!  Sorry for letting this flounder, I got caught up in some other things, and we have a workaround locally that made this less pressing.  But I'd really like to get this fixed up soon.

2019-07-18 15:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitter/elephant-bird?pullRequest=483) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twitter/elephant-bird?pullRequest=483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitter/elephant-bird?pullRequest=483) it.</sub>

2022-07-04 20:09 UTC, closed without merging